---
title: "ice"
format: html
editor: visual
---

```{r}
library(here)
library(tidyverse)
library(janitor)
library(ggbeeswarm)
```

```{r}
meteorological_data <- read_csv(here("data", "ntl20_v6.csv"))
ice_cover_duration <- read_csv(here("data", "ntl33_v7.csv"), 
                                    na = "-999")

```

```{r}
# Create a visualization that compares ice duration across different lakes in the Madison Lake Area. Include both the actual ice duration values and some representation of summary statistics for each lake. Careful if you use a boxplot over a jitter or beeswarm - what values might be doubly represented? Can you find an argument that would help you remove those from the boxplot?

ggplot(data = ice_cover_duration, aes(x = lakeid, y = ice_duration)) +
  geom_jitter(width = 0.2, color = "gray50") +
  geom_boxplot(width = 0.3, fill = NA, size = 1, outlier.color = NA) +
  theme_classic()


```

```{r}
# Find the mean ice cover duration in Madison Lake Area by year (i.e., you’ll only be grouping by the year variable here). Understanding check: what are you finding the mean of here? Why are there multiple observations for each year?)

ice_mean <- ice_cover_duration %>% 
  group_by(year4) %>% 
  mutate(mean_ice_cover = mean(ice_duration, na.rm = TRUE))

# Create an exploratory visualization of mean ice cover duration by year for the Madison Lake Area. Add a sentence or two below this exploratory graph describing the overall trend(s) you observe.

ggplot(data = ice_mean, 
       aes(x = year4, 
           y = mean_ice_cover)) +
  geom_line()

# Find the mean air temperature (using the daily average air temperature - adjusted) in Madison Lake Area by year using only observations from winter months (December, January, February)

weather_summary <- meteorological_data %>% 
  filter(month %in% c(12, 1, 2)) %>% 
  group_by(year4) %>% 
  summarize(mean_temp = mean(ave_air_temp_adjusted, na.rm = TRUE))

# Create an exploratory visualization of mean winter temperatures for the Madison Lake Area. Add a sentence or two below this exploratory graph describing the overall trend(s) you observe.

ggplot(data = weather_summary,
       aes(x = year4,
           y = mean_temp)) +
  geom_line()

# Join the mean winter air temperatures to the mean ice cover duration data you found above

ice_weather_join <- full_join(weather_summary, ice_mean)

# Create an exploratory scatterplot of mean winter temperatures versus mean ice duration. Add a sentence or two below this exploratory graph describing the overall trend(s) you observe.

ggplot(data = ice_weather_join,
       aes(x = mean_temp,
           y = mean_ice_cover)) +
  geom_point(aes(color = lakeid)) 

# Explore thaw dates since 1970. Create a subset of the ice cover duration data since 1970 (ok to include 1970), then convert the ice_off column to a Date. Use lubridate::yday() to pull the numeric day of the year from that Date. Create an exploratory plot of the ice off day (numeric day-of-the-year) from 1970 - present. Add a sentence or two below this exploratory graph describing the overall trend(s) you observe.

ice_1970 <- ice_cover_duration %>% 
  filter(year4 >= 1970) %>% 
  mutate(ice_off = lubridate::mdy(ice_off)) %>% 
  mutate(ice_off_day = lubridate::day(ice_off))


ggplot(data = ice_1970,
       aes(x = ice_off_day,
           y = year4)) +
  geom_point(aes(color = lakeid)) +
  facet_wrap(~lakeid) +
  theme_classic() 

```
